application: prueba
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheet
  static_dir: estilos
  
- url: /images
  static_dir: static/images

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: javascript

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest